# ============================================================
# Grafana datasource — Prometheus (provisionado automaticamente)
# ============================================================

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: '15s'     # alinha com o scrape_interval do Prometheus
      httpMethod: POST
